import type { Metadata } from "next";
import "./globals.css";
import '@/styles/global.scss';
import Navbar from '@/components/Navbar';

export const metadata: Metadata = {
  title: "pkq's portfolio",
  // description: "Generated by create next app",
  appleWebApp: {
    title: "pkq",
    capable: true,
    statusBarStyle: "default",
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {/* <GradientBackground/> */}
        <main>{children}</main>
        {/* <div className="noise"></div> */}
      </body>
    </html>
  );
}